name: Post Merge
on:
  push:
    branches:
    - main
permissions:
  contents: read
  security-events: write
jobs:
  codeql:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - uses: github/codeql-action/init@v2
      with:
        languages: go
    - uses: github/codeql-action/autobuild@v2
    - uses: github/codeql-action/analyze@v2
  scorecard:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - uses: ossf/scorecard-action@v1.1.2
      with:
        results_file: results.sarif
        results_format: sarif
    - uses: actions/upload-artifact@v3
      with:
        name: SARIF file
        path: results.sarif
        retention-days: 5
    - uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
