name: Pull Request
on: pull_request
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - uses: actions/setup-go@v3
      with:
        go-version: '~1.19'
    - uses: golangci/golangci-lint-action@v3
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - uses: actions/setup-go@v3
      with:
        go-version: '~1.19'
    - run: go build -v ./...
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - uses: actions/setup-go@v3
      with:
        go-version: '~1.19'
    - run: go test -v ./...
    - run: go vet ./...
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: actions/dependency-review-action@v2
